## File configuration for the plugin ServerTools ##

# Spawn management
spawn_location:
  x: 0.0
  y: 65.0
  z: 0.0
  pitch: 0.0
  yaw: 0.0
  world: 'world'
respawn_to_spawn_location: true

# Informations about color management :
#
# Each message prefix has a specific prefix that indicate the default color and prefix of the message :
# - "normal": default color (white: §f) - No prefix
# - "info_": yellow color (§e) - Info prefix of SimpleDevAPI
# - "cmd_": yellow color (§e) - No prefix (use in help page of commands)
# - "success_": green color (§a) - Success prefix of SimpleDevAPI
# - "failure_": red color (§c) - Failure prefix of SimpleDevAPI
# - "warning_": red color (§c) - Warning prefix of SimpleDevAPI
# - "error_": red color (§c) - Error prefix of SimpleDevAPI
# - "other_": couleur et préfixe indéterminé initiaux indéterminés
#
# Note: §r (reset formatter) will reset the message color to the default color specific to each type of message
# Example: Info message => "This message is yellow, §cRed now, §rYellow again"
messages:
  commands:
    broadcast:
      normal_prefix: '§7[§4§lAnnonce§7] §f'
    gc:
      info_header: '§6+§r------------- §aETAT SERVEUR §r-------------§6+'
      info_time_server_running: '§6Durée de fonctionnement : §c{Time_Running}'
      info_current_tps: '§6TPS actuels : §c{Tps_Value} {Tps_Indicator}'
      info_max_memory: '§6Mémoire maximale : §c{Max_Memory}§6 Mo'
      info_used_memory: '§6Mémoire utilisée : §c{Used_Memory}§6 Mo'
      info_free_memory: '§6Mémoire libre : §c{Max_Memory}§6 Mo'
      info_world_template: '§bMonde §6{Name} "§c{Type}§6" : §c{Number_Chunks_Loaded}§6 chunks, §c{Number_Entities}§6 entités, §c{Number_Tiles}§6 tiles'
      info_footer: '§6+§r--------------------------------------§6+'
    hat:
      cmd_arg_remove_desc: 'Retire votre chapeau'
      info_remove_done: 'Vous avez retiré votre chapeau !'
      success_message: 'L''item dans votre main est désormais sur votre tête !'
      warning_no_item_in_main_hand: 'Vous n''avez aucun item dans votre main principale !'
    killall:
      cmd_arg_entities_desc: 'Spécifie le type d''entités à supprimer'
      cmd_arg_entities_location_desc: 'Spécifie la portée de suppression des entités'
      info_kill_all_on_server: 'Vous avez supprimé {Number_Entities} entités sur le serveur.'
      info_kill_entities_on_server: 'Vous avez supprimé {Number_Entities} {Entities_Type} sur le serveur.'
      info_kill_all_in_world: 'Vous avez supprimé {Number_Entities} entités dans le monde {World}.'
      info_kill_entities_in_world: 'Vous avez supprimé {Number_Entities} {Entities_Type} dans le monde {World}.'
      info_kill_all_in_world_with_radius: 'Vous avez supprimé {Number_Entities} entités dans le monde {World} dans un rayon de {Radius} blocs.'
      info_kill_entities_in_world_with_radius: 'Vous avez supprimé {Number_Entities} {Entities_Type} dans le monde {World} dans un rayon de {Radius} blocs.'
    ping:
      cmd_desc: 'Vous indique la latence du joueur ciblé'
      info_ping_himself: '§6Pong ! §8» §c{Ping} ms'
      info_ping_target: 'Temps de réponse du joueur §b{Player} §e: §c{Ping} ms'
    seen:
      cmd_desc: 'Affiche les informations sur l''ip du joueur ciblé'
      normal_unknow_tag: 'Inconnue'
      other_header_info_ip: 'Informations sur l''IP'
      other_pseudo: 'Pseudo'
      other_last_ip_know: 'Dernière IP connue'
      other_location: 'Localisation'
      other_last_connection: 'Dernière connexion'
      other_connected: '§aConnecté'
      other_last_connection_time: 'Il y a {Last_Connection_Time}'
      other_list_players_with_same_ip: '§6Liste des joueurs utilisant la même adresse IP :'
      error_invalid_input_or_unkown_target: 'Saisie incorrecte ou joueur/ip inconnu(e).'
    suicide:
      failure_message: 'Vous vous êtes suicidé...'
    whois: 